services:
  app:
    restart: unless-stopped
    # domainname: mydomain.com # if you want to use your own domain
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - target: 3000
        mode: ingress
        published: 3000

    healthcheck:
      test: wget -q --spider http://localhost:3000/ || exit 1

    deploy:
      resources:
        reservations:
          cpus: '0.50'
          memory: 512M

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    ports:
      - mode: host
        target: 5432
        published: 5432

  mailer:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025